<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
	<title>Project Dependencies</title>
	<link href="style.css" rel="stylesheet"/>
	<?php include "./data/consts.php"; ?>
	<?php include "./process.php"; ?>
</head>

<body>

<table class="wiki">
<?php include "./draw.php"; ?>
</table>

<p>This table uses the <a href="https://repology.org/">Repology (https://repology.org/)</a> version tracking service, and thus versions displayed should be automatically kept up-to-date. Incorrect versions should be reported to them.</p>

<dl>
<dt><span style="background: #e00000; color: #fff; padding: 0.1em 0; border-radius: 3px;">
	<span style="background:linear-gradient(rgba(73,73,73,.1), rgba(0,0,0,.1)); padding: 0.1em 0.2em; border-radius: 3px;"><b>Bright Red/Scarlet</b></span>
</span></dt>
<dd>Package provided does not meet the project's minimum required version.<br/><br/></dd>

<dt><span style="background: #e05d44; color: #fff; padding: 0.1em 0; border-radius: 3px;">
	<span style="background:linear-gradient(rgba(73,73,73,.1), rgba(0,0,0,.1)); padding: 0.1em 0.2em; border-radius: 3px;"><b>Faded Red</b></span>
</span></dt>
<dd>Package provided is not the latest stable release (as determined by <i>Repology</i>).<br/><br/></dd>

<dt><span style="background: #4c1; color: #fff; padding: 0.1em 0; border-radius: 3px;">
	<span style="background:linear-gradient(rgba(73,73,73,.1), rgba(0,0,0,.1)); padding: 0.1em 0.2em; border-radius: 3px;"><b>Green</b></span>
</span></dt>
<dd>Package provided is the latest stable release (as determined by <i>Repology</i>).<br/><br/></dd>

<dt><span style="background: #9f9f9f; color: #fff; padding: 0.1em 0; border-radius: 3px;">
	<span style="background:linear-gradient(rgba(73,73,73,.1), rgba(0,0,0,.1)); padding: 0.1em 0.2em; border-radius: 3px;"><b>Light Grey</b></span>
</span></dt>
<dd>Package provided has a non-standard version.<br/><br/></dd>

<dt><span style="background: #555; color: #fff; padding: 0.1em 0; border-radius: 3px;">
	<span style="background:linear-gradient(rgba(73,73,73,.1), rgba(0,0,0,.1)); padding: 0.1em 0.2em; border-radius: 3px;"><b>Dark Grey</b></span>
</span></dt>
<dd>Package is not available from this repository.</dd>
</dl>

<p>This page was inspired by the <a href="https://d.pidgin.im/wiki/Dependencies/3.0.0">dependencies page</a> for <i>Pidgeon 3.0.0</i>, which uses the same service.</p>

<p>The table was generated by a script, the code of which can be found <a href="https://github.com/s0600204/ProjectDependenciesTable">here</a>. The content, however, is dependent on whoever's running the script on their server. Contact them to add or remove libraries or displayed distributions.</p>

<h4>Disclaimer:</h4>
<p>I am not responsible for the content or security of external links. (And all links on this page are external.)</p>

</body>
</html>
